### ISSUE TITLE
No closing body and html tags

### ISSUE THREAD

**Issue by jurbank** [growthemes/codelab#5]
I was just wondering why the code lab theme doesn't have closing body and html tags.

**Comment by jeremydw** [comment]
Good question -- this is something we might update at some point however per the HTML 5 spec both the `body` and `html` tags are "optional" tags meaning they don't require closing in source code.

While it's not a huge deal, this approach follows the "less is more" approach as it just requires a little less reading of the source code.

Some discussion:
https://news.ycombinator.com/item?id=12520674
https://news.ycombinator.com/item?id=677125

That said, the "do one thing when X and another when Y" concept (first comment in the first link) is something I agree with, which is why I mentioned we might change this for future themes/projects.
